### ISSUE TITLE
[ALLOW] Nvidia

### ISSUE THREAD

**Issue by Ealenn** [Ealenn/AdGuard-Home-List#24]
**Describe**

@madindehead have added nvidia domain to the allow list on his fork. 

**Domain**
```
@@||nvidia.com^$important
```

**Additional context**
Identify why and who block this domain.

**Comment by madindehead** [comment]
I was having some issues with accessing and downloading files from a section of the Nvidia website. In order to rule out AdGuard Home I added Nvidia.com (I had also disabled my blocker, but needed it up as I was looking at other pages where I needed the protection). 

I think I can probably remove it again.

**Comment by Ealenn** [comment]
Thanks for your feedback ❤️

I'll check some domains on local setup soon. I planned to clean up a maximum of poisonings lists (as you can see, I added some issues to debug the generated files).

If you have any issue, don't hesitate to check your AdGuard log and ping me 🙏
